import tkinter.messagebox
from tkinter import *
from tkinter.font import BOLD


def slider(value):
    r = red_scale.get()
    g = green_scale.get()
    b = blue_scale.get()
    rgb = f'{r},{g},{b}'
    code = "#%02x%02x%02x" % (r, g, b)
    colorlabel.config(bg = code)
    rgb_entry.delete(0,END)
    rgb_entry.insert(0,rgb)
def onClick():
    tkinter.messagebox.showinfo("copy to clipboard", "your rgb color code ("+rgb_entry.get()+") is copied to clipboard")
    clip = Tk()
    clip.withdraw()
    clip.clipboard_clear()
    clip.clipboard_append(rgb_entry.get())
    clip.destroy()
root = Tk()
root.title("Color Picker")
root.geometry("400x400+200+200")
colorlabel = Label(root, text = "Color", bg = "black", fg = "white", width=50, height=10, bd=1, relief=None)
colorlabel.pack(pady=5)
frame = Frame(root, bd = 1, relief = None)
frame.pack(pady=5)
red_label = Label(frame, text = "Red", fg="red" , font = ("Arial", 12))
red_label.grid(row=0, column=0)
red_scale = Scale(frame, from_=0, to=255, orient=HORIZONTAL, command=slider, fg = "red")
red_scale.grid(row=0, column=1)
green_label = Label(frame, text = "Green", fg="green" , font = ("Arial", 12))
green_label.grid(row=1, column=0)
green_scale = Scale(frame, from_=0, to=255, orient=HORIZONTAL, command=slider, fg = "green")
green_scale.grid(row=1, column=1)
blue_label = Label(frame, text = "Blue", fg="blue" , font = ("Arial", 12))
blue_label.grid(row=2, column=0)
blue_scale = Scale(frame, from_=0, to=255, orient=HORIZONTAL, command=slider, fg = "blue")
blue_scale.grid(row=2, column=1)
frame2 = Frame (root, bd = 1, relief = None)
frame2.pack(pady=5)
rgb_label = Label(frame2, text = "RGB CODE   :", font = ("Arial", 12, BOLD))
rgb_label.grid(row=2, column=0)
rgb_entry = Entry(frame2, width=20, font = ("Arial", 12))
rgb_entry.grid(row=2, column=1, padx=5)
rgb_entry.insert(END,"")
copy = Button(frame2, text = "Copy", command = onClick, font = ("Arial", 12))
copy.grid(row=2, column=2, padx=5)
root.mainloop()